project:
  type: default

format:
  revealjs:
    theme: [default, slides/theme/ncsu.scss]
    slide-number: true
    transition: fade
    background-transition: fade
    code-overflow: wrap
    toc: false
    footer: "North Carolina Astronomers' Meeting 2025"

editor: visual
